frame_id: world_frame
point_cloud_descriptions:
  - x: 2.5
    y: -0.4
    z: 0.36
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.1
    w: 0.19
    h: 0.0
    resolution: 0.001
  - x: 2.0
    y: -0.7
    z: 0.15
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.2
    w: 0.1
    h: 0.0
    resolution: 0.001
  - x: 1.9
    y: -0.6
    z: 0.25
    rx: 0.0
    ry: 0.0
    rz: 0.1
    l: 0.2
    w: 0.5
    h: 0.0
    resolution: 0.001